### ISSUE TITLE
suggest 2.1 tags? 

### ISSUE THREAD

**Issue by dinobossytnew** [Angelillo15/zAngelTags#1]
you could add the following commands and functions to the plugin?

add custom menu so that the tags and menu can be decorated with crystals inside.

add commands like:
/tags force set %player% %tag%.
/tags force remove %player% %tag%
add support for itemsadder effect text by discord we can talk about this function I can give you the api to work and add support DinoBoss#6985 .

**Comment by Lunna5** [comment]
mmm, the force commands i will see it today or tomorrow, and the items adder text you mean this? ![Spigot](https://i.imgur.com/Fdvq3Xt.gif)

**Comment by dinobossytnew** [comment]
yes

**Comment by dinobossytnew** [comment]
Could you also add that the tag menu can be customized plus add heads among other things?

**Comment by Lunna5** [comment]
Hola, he visto tu github y veo que eres de habla hispana, si no te importa nos podemos comunicar asi, el tema de los menus tengo previsto que para la 4.0 sea completamente customizable

**Comment by dinobossytnew** [comment]
ok vale no pasa nada jaja xd, si soy español pero si se te da mal avisame 3>

**Comment by dinobossytnew** [comment]
y lo de migrar tags no se si podrias hacerlo.

**Comment by Lunna5** [comment]
> y lo de migrar tags no se si podrias hacerlo.

Con migrar a que te refieres ?

**Comment by dinobossytnew** [comment]
pues migrar tags ya hechos de otro plugin a tu plugin, no que sea perfecto pero si al menos el lore y las mayoria de webdas.

**Comment by Lunna5** [comment]
Vale, lo mirare, si no le importa cierro la issue por ahora

**Comment by dinobossytnew** [comment]
ok no pasa nada , mientras si puedes añadir el ticket de github puede estar cerrado y seguimos hablamos.
